project:
  type: website

execute:
  freeze: auto

website:
  page-navigation: true
  title: "Statistics"
  description: "Homepage for Statistics at HdM Stuttgart, WS 23/24."
  open-graph: true
  image: "/images/logo.png"
  favicon: "/images/logo.png"
  search:
    type: overlay  
  page-footer:
    left: |
      © [Jan Kirenz](https://www.kirenz.com/), 2023
    center:
      - text: "Schedule"
        href: index.qmd
      - text: "Syllabus"
        href: course-syllabus.qmd  
    right:
      - icon: person-circle
      - text: "Moodle"
        href: https://moodle.hdm-stuttgart.de/login/index.php
        aria-label: Moodle    
#    background: "#325b74"    


  sidebar:
#    background: "#325b74"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: person-fill
        text: "Moodle"
        href: https://moodle.hdm-stuttgart.de/course/view.php?id=2464

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: index.qmd
            text: Schedule

      - section: "Programming"
        contents:
          - href: programming-requirements.qmd
            text: Requirements


format:
  html:
    toc: true
    theme:
      light: [cosmo, style/course.scss]
      dark: [cosmo, style/course.scss, style/dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap