---
title: "Syllabus"
---



## Course info

|           | Day       | Time              | Location |
|-----------|-----------|-------------------|----------|
| Lecture   | Tuesday    | 16:00  - 17:30  |  108  |



## Learning objectives

Gain experience in exploratory data analysis, predictive modeling, and statistical inference while working on problems and case studies inspired by and based on real-world questions. 

By the end of the semester, you will be able to...

-   obtain, explore, visualize, and analyze data in Python to investigate patterns.
-   fit and evaluate linear and logistic regression models to make predictions.
-   use statistical methods to test hypothesis.


## Where to get help

- If you have a question during lecture, feel free to ask it! 
- Outside of class, any general questions about course content or assignments should be posted on the Moodle course forum.
- Emails should be reserved for questions not appropriate for the public forum. **If you email me, please include the name of our course in the subject line.** 

Check out the [Support](course-support.qmd) page for more resources.

## Textbooks

Textbook for the course:

- [Introduction to Modern Statistics](https://openintro-ims.netlify.app/) by Mine Çetinkaya-Rundel and Johanna Hardin


## Exam {#sec-exams}

There will be one E-exam in Moodle.

- E-Exam (90 minutes at the end of the semester. 60% market research and 40% statistics)


More details about the exam will be given during the semester.


## Grading

The final grade will be determined based on the following thresholds:

|  Grade       | Final Course Grade |
|--------------|--------------------|
| 1.0           | 96 - 100          |
| 1.3           | 91 - 95           |
| 1.7           | 85 - 90           |
| 2.0           | 80 - 84           |
| 2.3           | 75 - 79           |
| 2.7           | 70 - 74           |
| 3.0           | 65 - 69           |
| 3.3           | 60 - 64           |
| 3.7           | 55 - 59           |
| 4.0            | 50 - 54          |
| 4.7           | 15 - 49           |
| 5.0            | 0 - 14           |


